title: TamrielCraft
description: >-
  Welcome to TamrielCraft â€” a Minecraft server recreating the Elder Scrolls universe.

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

plugins:
  - jekyll-include-cache

# Default ghpages/Jekyll
markdown: kramdown
highlighter: rouge

# Disable/minimize these to get started
minimal_mistakes_skin: "default"
locale: "en-US"

footer:
  links:
    - label: "YouTube"
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@TamrielCraftOfficial"
    - label: "Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/tamrielcraft/"
    - label: "PlanetMinecraft"
      icon: "fa-solid fa-earth-europe" #Doesn't exist so need an option.
      url: "https://www.planetminecraft.com/server/tamrielcraft/"
    - label: "Discord"
      icon: "fa-brands fa-discord"
      url: "https://discord.gg/ApShrYn"

author:
  name: "TamrielCraft"
  avatar: "/assets/images/tc_profile256_clean_yellow.jpg"
